### PR TITLE
Added image replacement

### PR DESCRIPTION
**Pull request by LeeConnelly12**
Extension uses google's search API to get the first 10 results of Cabo Daciolo and gets their images.
This PR is for issue #11

### CODE REVIEW

**Comment by rudnetto** [comment]
Hello @LeeConnelly12, thanks for the contribution!

One thing that is missing is resizing the Daciolo's images to the original size of  elements.
When openin github, for example, the new image occupies a different size of the original element.

**Comment by LeeConnelly12** [comment]
@rudnetto ok the images should stay the same size when they're changed now

**Comment by rudnetto** [comment]
Thanks for the addition @LeeConnelly12, gonna merge it!

Resolve issue #11

**Comment by rudnetto** [comment]
@LeeConnelly12 I'd only ask you to rebase your repo or create another pull request, because your code is conflicting with other PR that was accepted earlier.

**Comment by LeeConnelly12** [comment]
@rudnetto Can you try now?

**Comment by rudnetto** [comment]
@LeeConnelly12 tested it locally and everything seems okay 😄 

Resolves #11

**Pull request merged**
